library(edgeR)
x <- read.delim("nmrexpression.txt",row.names="gene")
treat<- factor(c("A","A","A","B","B","B","C","C","C","D","D","D","E","E","E","F","F","F"))
time=factor(c("8","8","8","8","8","8","8","8","8","48","48","48","48","48","48","48","48","48"))
repli=factor(c("1","2","3","1","2","3","1","2","3","1","2","3","1","2","3","1","2","3"))
y <- DGEList(counts=x) 
keep <- rowSums(cpm(y)>1) >= 2 
y <- y[keep, , keep.lib.sizes=FALSE]
y <- calcNormFactors(y) 
#design <- model.matrix((~0+treat))
design <- model.matrix((~0+treat+repli))
y <- estimateDisp(y,design,robust=TRUE)
y$common.dispersion
plotMDS(y)
fit <- glmQLFit(y, design,robust=TRUE) 
#qlf <- glmQLFTest(fit, contrast=c(-1,1,0,0,0,0))
qlf1 <- glmQLFTest(fit, contrast=c(-1,1,0,0,0,0,0,0)) 
summary(decideTests(qlf1))
topTags(qlf1)
qlf2 <- glmQLFTest(fit, contrast=c(-1,0,1,0,0,0,0,0)) 
summary(decideTests(qlf2))
topTags(qlf2)
qlf3 <- glmQLFTest(fit, contrast=c(0,0,0,-1,1,0,0,0)) 
summary(decideTests(qlf3))
topTags(qlf3)
qlf4 <- glmQLFTest(fit, contrast=c(0,0,0,-1,0,1,0,0)) 
summary(decideTests(qlf4))
topTags(qlf4)